apiVersion: v1
kind: Service
metadata:
  name: {{ include "quote-app.fullname" . }}-frontend
  labels:
    {{- include "quote-app.labels" . | nindent 4 }}
spec:
  selector:
    app: quote-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}
