{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quote-app.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "quote-app.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.port }}
          - path: /quote
            pathType: Prefix
            backend:
              service:
                name: {{ include "quote-app.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.port }}
{{- end }}
